config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resource :user, only: %i[show]
  resource :wallet, only: %i[show new create]
  resource :account, only: %i[show new create]
  resources :contracts, only: %i[new create]
  resources :stable_coins, only: %i[new create]
  resources :account_transactions, only: %i[index]
  resources :wallet_transactions, only: %i[index]
  resources :issuance_transactions, only: %i[index]
  resources :payment_transactions, only: %i[index]
  resources :withdrawal_transactions, only: %i[index]

  namespace :api do
    post 'payment/create', to: 'payments#create'
    post 'payment/confirm', to: 'payments#confirm'

    post 'withdraw/create', to: 'withdraws#create'
    post 'withdraw/confirm', to: 'withdraws#confirm'

    resources :issuance_requests, only: %i[show]
    resources :payment_requests, only: %i[show]
    resources :withdrawal_requests, only: %i[show]
  end
end

app/models/user.rb
# frozen_string_literal: true

# 顧客モデル
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 255 }, uniqueness: true

  has_one :account
  has_one :wallet
  belongs_to :did
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :signed_in?, only: %i[show]

  def show
    @user = current_user
  end

  def new; end

  def create
    did = Did.create!(short_form: user_params['did'])
    user = User.create!(username: user_params['username'], did:)
    user.build_account.save!
    user.build_wallet.save!

    sign_in(user)

    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :did)
  end
end

app/views/users/new.html.erb
<h2>
  Sign Up
</h2>

<%= form_with scope: :user, url: signup_path do |form| %>
  <div>
    <%= form.text_field :username, placeholder: "User Name", required: true %>
    <%= form.text_field :did, placeholder: "DID", required: true %>

    <%= form.submit "Sign Up" %>

    <div>
      <p>
        Already have an account?
        <%= link_to "Login", login_path %>
      </p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <div>
    <h2>
      マイページ
    </h2>

    <div>
      <div>
        <%= "ユーザーネーム: #{current_user.username}" %>
      </div>
    </div>

    <div>
      <%= link_to account_transactions_path do %>
        <div>
          <div>
            <%= "現金残高: #{number_to_currency(current_user.account.balance, precision: 0)}" %>
          </div>
        </div>
      <% end %>
    </div>

    <% if current_user.wallet.present? %>
      <div>
        <%= link_to wallet_transactions_path do %>
          <div>
            <div>
              <%= "ステーブルコイン残高: #{number_to_currency(current_user.wallet.balance, precision: 0)}" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <h3>
      ステーブルコイン発行
    </h3>
    <%= form_with scope: :stable_coin, url: stable_coins_path do |form| %>
      <div>
        <%= form.number_field :amount, placeholder: "金額", required: true %>
        <%= form.submit "発行" %>
      </div>
    <% end %>
  </div>
</div>