config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resource :user, only: %i[show]
  resource :wallet, only: %i[show new create]
  resource :account, only: %i[show new create]
  resources :contracts, only: %i[new create]
  resources :stable_coins, only: %i[new create]
  resources :account_transactions, only: %i[index]
  resources :wallet_transactions, only: %i[index]
  resources :issuance_transactions, only: %i[index]
  resources :payment_transactions, only: %i[index]
  resources :withdrawal_transactions, only: %i[index]

  namespace :api do
    post 'payment/create', to: 'payments#create'
    post 'payment/confirm', to: 'payments#confirm'

    post 'withdraw/create', to: 'withdraws#create'
    post 'withdraw/confirm', to: 'withdraws#confirm'

    resources :issuance_requests, only: %i[show]
    resources :payment_requests, only: %i[show]
    resources :withdrawal_requests, only: %i[show]
  end
end

app/models/account.rb
# frozen_string_literal: true

# 顧客銀行口座モデル
class Account < ApplicationRecord
  validates :balance, presence: true
  validates :account_number, presence: true
  validates :branch_code, presence: true
  validates :branch_name, presence: true

  belongs_to :user

  has_many :account_transactions

  after_initialize do
    self.balance ||= 0.0
    self.account_number ||= "1#{format('%06d', SecureRandom.random_number(10**6))}"
    self.branch_code ||= '101'
    self.branch_name ||= '本店'
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :signed_in?, only: %i[show new create]

  def new
    @account_transactions = current_user.account.account_transaction.order(transaction_time: :DESC)
  end


  def create
    amount = deposit_params['amount'].to_i
    account = current_user.account
    account.update!(balance: account.balance + amount)

    AccountTransaction.create(
      account:,
      amount:,
      transaction_type: 0,
      transaction_time: Time.current
    )
    redirect_to user_path
  end

  private

  def deposit_params
    params.require(:account).permit(:amount)
  end
end

app/views/accounts/new.html.erb
<h2>
  Deposit
</h2>

<div>
  <div>
    Account Balance
  </div>
  <div>
    <%= number_to_currency(current_user.account.balance, precision: 0) %>
  </div>
</div>

<%= form_with scope: :account, url: account_path do |form| %>
  <div>
    <%= form.number_field :amount, placeholder: "amount", required: true %>
    <%= form.submit "Deposit" %>
  </div>
<% end %>

<table>
  <tr>
    <th>ID</th>
    <th>amount</th>
    <th>transaction_type</th>
    <th>取引日時</th>
  </tr>
<% @account_transactions.each do |account_transaction| %>
  <tr>
  <td><%= account_transaction.id %></td>
  <td><%= account_transaction.amount %></td>
  <td><%= account_transaction.transaction_type %></td>
  <td><%= account_transaction.transaction_time %></td>
  </tr>
<% end %>
</table>